module.exports = {
  LOGIN_USER: "LOGIN_USER",
  ERROR_RECEIVED: "RECEIVE_ERROR",
  LOGOUT_USER: "LOGOUT_USER",
  DESTROY_USER: "DESTROY_USER",
  CREATE_USER: "CREATE_USER",
  RECEIVE_USERS: "RECEIVE_USERS",
  RECEIVE_SINGLE_USER: "RECEIVE_SINGLE_USER",
  RECEIVE_CURRENT_USER: "RECEIVE_CURRENT_USER"
};
